### ISSUE TITLE
Can raspberrypi use it?

### ISSUE THREAD

**Issue by doubiiot** [dixel/wifi-linux#1]

**Comment by dixel** [comment]
I've checked it and for rapsbian version that I have it doesn't work because there is no NetworkManager there:
```
$ sudo systemctl status NetworkManager.service
● NetworkManager.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
```
Should work if it's in place, but internet recommends more lightweight solutions for managing internet connections on RPi (https://raspberrypi.stackexchange.com/a/9750). This tool itself was written due to the "monopoly" NetworkManager had on linux machines. If there is already something more appropriate for the same purposes - I'd use it instead of network-manager+dbus.
